name: "Build"

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
            node-version: "16"
      - name: NPM install
        run: npm install
      - name: Build
        run: npm run build
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: WhatsappChatConverter ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # releaseId: ${{ steps.create_release.outputs.upload_url }}
          args: 'WhatsappChatConverter-*'
      
