name: "Build"

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
            node-version: "16"
      - name: NPM install
        run: npm install
      - name: Build
        run: npm run build
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: WhatsappChatConverter ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Release binaries
      - run: |
          set -x
          assets=()
          for asset in ./WhatsappChatConverter-*; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
